// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ih92-l22KGu8gibCvbtsTPx7Kb3aD-I',
    appId: '1:212168037354:web:e4826cd6ac1c6bece2d893',
    messagingSenderId: '212168037354',
    projectId: 'movies-app-by-fatoma',
    authDomain: 'movies-app-by-fatoma.firebaseapp.com',
    storageBucket: 'movies-app-by-fatoma.firebasestorage.app',
    measurementId: 'G-8GQJDM2HEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBphIYr7csRNsyZ_WDhhXCuupOathG2884',
    appId: '1:212168037354:android:80e70352a2e9eedde2d893',
    messagingSenderId: '212168037354',
    projectId: 'movies-app-by-fatoma',
    storageBucket: 'movies-app-by-fatoma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPUnfsXToOEkKXYtTvxrdJ2zKms0JSuPY',
    appId: '1:212168037354:ios:29075ce0ee2b9bfde2d893',
    messagingSenderId: '212168037354',
    projectId: 'movies-app-by-fatoma',
    storageBucket: 'movies-app-by-fatoma.firebasestorage.app',
    iosClientId: '212168037354-ipdcvn5c22uajja2712k7s3j0kl2dfin.apps.googleusercontent.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPUnfsXToOEkKXYtTvxrdJ2zKms0JSuPY',
    appId: '1:212168037354:ios:29075ce0ee2b9bfde2d893',
    messagingSenderId: '212168037354',
    projectId: 'movies-app-by-fatoma',
    storageBucket: 'movies-app-by-fatoma.firebasestorage.app',
    iosClientId: '212168037354-ipdcvn5c22uajja2712k7s3j0kl2dfin.apps.googleusercontent.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0ih92-l22KGu8gibCvbtsTPx7Kb3aD-I',
    appId: '1:212168037354:web:10781c9adc82ce35e2d893',
    messagingSenderId: '212168037354',
    projectId: 'movies-app-by-fatoma',
    authDomain: 'movies-app-by-fatoma.firebaseapp.com',
    storageBucket: 'movies-app-by-fatoma.firebasestorage.app',
    measurementId: 'G-25JVY0ZYZ9',
  );
}
